### ISSUE TITLE
Log organisation in sentry

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/replication-backend#111]
The logs sent to Sentry do not contain the information to know to which organisation the logs belongs. This is an issue for all backends, replication-backend and query-backend.

add properties to Sentry logger:
- URL of request (and/or realm, i.e. instance name)
- release (version)
  - currently shows as "undefined" in Sentry
  - code seems to assume `process.env.npm_package_version` can be used but even if this would be defined, we currently don't update package.json version on releases ...

Suggested approach:
- [ ] add "realm" as sentry.environment. This makes filtering in Sentry UI then very easy.
  - TODO: how do we get the "realm"?
- [ ] add semantic-release to backend repos, let it version and update the package.json
- [ ] figure out how to get the package.json version to use it in code for the release

**Comment by sleidig** [comment]
e.g. https://aam-digital.sentry.io/issues/4471309463 (shows some hash as server_name)
