### ISSUE TITLE
Re-sync after changed permissions

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/replication-backend#7]
Once the permissions change, the sync should be restarted for each client.

**Comment by TheSlimvReal** [comment]
**TODO server side:**
When a user gains access to more document after the permissions are changed, the replication protocol should automatically ensure that the user gets the document synced. This can be achieved by deleting the replication history in the `_local` database.
- [ ] Execute the `clearLocal` endpoint/function whenever the permission rules change.

**TODO client side:**
When a user looses access to documents after the permissions are changed, they should be automatically removed from the clients local database. Currently the only feasible way to achieve this, is to implement it on the client side. When deleting the documents the default `PouchDB` API might not be the right solution because it will create a new revision number that might cause problems in a later sync. Instead the document should be entirely deleted. Therefore a direct access to the `IndexedDB` might be necessary.
- [ ] When permissions change the client should somehow evaluate, to which documents it does not have access any more and completely delete them from the local device.

**Comment by sleidig** [comment]
also see #2300

**Comment by sleidig** [comment]
Somehow the current auto-triggering of clearLocal does not work correctly yet, although it's execution through a manual API call works.
