### ISSUE TITLE
File upload on just created entities

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/replication-backend#94]
When creating an entity and uploading a file at the same time (e.g. uploading a file in the "add new" process) creates an error because the attachment controller tries to load the existing document which does not exist yet. At the moment the `update` permissions are checked on the existing object. This should probably be extended for this case with a `create` permission check if no entity could be found - although the service doesn't know whether this entity will really be created.

**Comment by sleidig** [comment]
fixed via frontend: https://github.com/Aam-Digital/ndb-core/pull/2410
